/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Controlador.Cevaluacion;
import Controlador.Cgestion_amena;
import Controlador.Crecursos;
import Modelo.Mevaluacion;
import Modelo.Mgestion_amena;
import Modelo.Mrecursos;
import java.io.FileInputStream;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.UIManager;

/**
 *
 * @author LENOVO
 */
public class Gestion_amenazas extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_amenazas
     */
    public Gestion_amenazas() {
        initComponents();
        // inhabilitar botones minimizar, cerrar y maximizar
         getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        this.setLocationRelativeTo(null);
         ButtonGroup rbnitem1 = new ButtonGroup();
        rbnitem1.add(rbjustiitem51);
        rbnitem1.add(rbnojustiitem51);

        ButtonGroup rbnitem2 = new ButtonGroup();
        rbnitem2.add(rbjustiitem52);
        rbnitem2.add(rbnojustiitem52);

         ButtonGroup mv112 = new ButtonGroup();
        mv112.add(rbsi511);
        mv112.add(rbno511);

        ButtonGroup mv113 = new ButtonGroup();
        mv113.add(rbsi512);
        mv113.add(rbno512);

        ButtonGroup mv114 = new ButtonGroup();
        mv114.add(rbsi513);
        mv114.add(rbno513);

        ButtonGroup mv121 = new ButtonGroup();
        mv121.add(rbsi521);
        mv121.add(rbno521);
        
        
        
        noVisibles();
    }
    Mevaluacion ps= new Mevaluacion();
    Evaluacion_Ini gh= new Evaluacion_Ini();
            
    
    Mgestion_amena tr= new Mgestion_amena();
  public void noVisibles(){
       
       this.lblnocum51.setEnabled(false);
       this.lblnocum52.setEnabled(false);
       
       this.lblcum51.setEnabled(false);
       this.lblcum52.setEnabled(false);
       
       this.rbjustiitem51.setEnabled(false);
       this.rbjustiitem52.setEnabled(false);
       
       this.rbnojustiitem51.setEnabled(false);
       this.rbnojustiitem52.setEnabled(false);
       
       this.txtitem51.setEnabled(false);
       this.txtitem52.setEnabled(false);
       
       this.btnadjnoitem51.setEnabled(false);
       this.btnadjnoitem52.setEnabled(false);
       
      

       btnmv511.setEnabled(false);
       btnmv512.setEnabled(false);
       btnmv513.setEnabled(false);
       btnmv521.setEnabled(false);
         
       
   }
  
    Cevaluacion cm = new Cevaluacion();
 private void Validar(){
      
       if(tr.getI511().equals("")){
        
        JOptionPane.showMessageDialog(null,"El item 1 del estandar E5.1 no se ha diligenciado correctamente ");
        
    }
    
    if(tr.getI521().equals("")){
        
         JOptionPane.showMessageDialog(null,"El item 2 del estandar E5.1 no se ha diligenciado correctamente ");
        
    }
      
       if(!tr.getI511().equals("") && !tr.getI521().equals("")){
           
           int dialogButton =JOptionPane.showConfirmDialog(null, "Esta seguro que desea guardar las respuesta diligenciadas en la evaluacion inicial,"
                                                        + " recuerde que si acepta no podra volver a diligenciar este formulario hasta que comience una nueva E. inicial ");
           if(dialogButton == JOptionPane.YES_OPTION){     
           
           
            Cgestion_amena func = new Cgestion_amena();

        func.insertarItem51(tr);
       
        if(func.insertarItem52(tr)){
            JOptionPane.showMessageDialog(rootPane, "Se han registrado los items satisfactoriamente");

        }  

       ps.setE5(1);
       gh.config();
       int valo=10;
       ps.setBarra(ps.getBarra()+valo);
       this.dispose();
       gh.val=ps.getBarra();
        gh.empezar();
        
        cm.est_gestAmena(ps);
       gh.setVisible(true);
       gh.toFront();
           
           
           
           
           }
           
           
       }
      
      
      
      
  }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        lblnocum51 = new javax.swing.JLabel();
        lblcum51 = new javax.swing.JLabel();
        noaplicaitem51 = new javax.swing.JCheckBox();
        rbjustiitem51 = new javax.swing.JRadioButton();
        rbnojustiitem51 = new javax.swing.JRadioButton();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtitem51 = new javax.swing.JTextArea();
        btnadjnoitem51 = new javax.swing.JButton();
        jLabel74 = new javax.swing.JLabel();
        rbsi511 = new javax.swing.JRadioButton();
        rbno511 = new javax.swing.JRadioButton();
        btnmv511 = new javax.swing.JButton();
        jLabel75 = new javax.swing.JLabel();
        rbsi513 = new javax.swing.JRadioButton();
        rbno513 = new javax.swing.JRadioButton();
        btnmv513 = new javax.swing.JButton();
        rbsi512 = new javax.swing.JRadioButton();
        rbno512 = new javax.swing.JRadioButton();
        btnmv512 = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel70 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        lblnocum52 = new javax.swing.JLabel();
        lblcum52 = new javax.swing.JLabel();
        noaplicaitem52 = new javax.swing.JCheckBox();
        rbjustiitem52 = new javax.swing.JRadioButton();
        rbnojustiitem52 = new javax.swing.JRadioButton();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtitem52 = new javax.swing.JTextArea();
        btnadjnoitem52 = new javax.swing.JButton();
        jLabel83 = new javax.swing.JLabel();
        rbsi521 = new javax.swing.JRadioButton();
        rbno521 = new javax.swing.JRadioButton();
        btnmv521 = new javax.swing.JButton();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E5.1Plan de prevención, preparación y respuesta ante emergencias (10%)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18))); // NOI18N
        jPanel17.setToolTipText("");

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ítem 1:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 16))); // NOI18N

        jLabel72.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel72.setText("Modo de Verificación ");

        jLabel73.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel73.setText("Se cuenta con el plan de prevención y preparación ante emergencias (5%)");

        lblnocum51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Close.png"))); // NOI18N

        lblcum51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checked.png"))); // NOI18N

        noaplicaitem51.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        noaplicaitem51.setText("No Aplica");
        noaplicaitem51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noaplicaitem51ActionPerformed(evt);
            }
        });

        rbjustiitem51.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbjustiitem51.setText("Justifica");
        rbjustiitem51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbjustiitem51ActionPerformed(evt);
            }
        });

        rbnojustiitem51.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbnojustiitem51.setText("No justifica");
        rbnojustiitem51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnojustiitem51ActionPerformed(evt);
            }
        });

        txtitem51.setColumns(20);
        txtitem51.setRows(5);
        txtitem51.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtitem51KeyPressed(evt);
            }
        });
        jScrollPane15.setViewportView(txtitem51);

        btnadjnoitem51.setText("Adjuntar Doc");
        btnadjnoitem51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadjnoitem51ActionPerformed(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel74.setText("1. Solicitar el plan de prevención y respuesta ante emergencias, constatar su divulgación. ");

        rbsi511.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbsi511.setText("Cumple");
        rbsi511.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsi511ActionPerformed(evt);
            }
        });

        rbno511.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbno511.setText("No cumple");
        rbno511.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbno511ActionPerformed(evt);
            }
        });

        btnmv511.setText("Adjuntar Doc");
        btnmv511.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmv511ActionPerformed(evt);
            }
        });

        jLabel75.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        rbsi513.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbsi513.setText("Cumple");
        rbsi513.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsi513ActionPerformed(evt);
            }
        });

        rbno513.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbno513.setText("No cumple");
        rbno513.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbno513ActionPerformed(evt);
            }
        });

        btnmv513.setText("Adjuntar Doc");
        btnmv513.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmv513ActionPerformed(evt);
            }
        });

        rbsi512.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbsi512.setText("Cumple");
        rbsi512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsi512ActionPerformed(evt);
            }
        });

        rbno512.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbno512.setText("No cumple");
        rbno512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbno512ActionPerformed(evt);
            }
        });

        btnmv512.setText("Adjuntar Doc");
        btnmv512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmv512ActionPerformed(evt);
            }
        });

        jLabel77.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel77.setText("2. Verificar si existen los planos de las instalaciones que identifican áreas y salidas de emergencia y verificar si existe la debida señalización ");

        jLabel78.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel78.setText("de la empresa y los soportes que evidencien la realización de los simulacros.");

        jLabel79.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel79.setText("3. Verificar la realización de simulacros y análisis del mismo, validar que las mejoras hayan sido tenidas en el mejoramiento del plan.");

        jButton13.setText("Criterio");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblnocum51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcum51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel73)
                            .addComponent(jButton13)))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noaplicaitem51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbjustiitem51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbnojustiitem51)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadjnoitem51, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel79)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel77, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
                                .addGap(49, 49, 49))
                            .addComponent(jLabel78))
                        .addComponent(jLabel75)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(rbsi513)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbno513)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmv513))
                            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel19Layout.createSequentialGroup()
                                    .addComponent(rbsi511)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbno511)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnmv511))
                                .addGroup(jPanel19Layout.createSequentialGroup()
                                    .addComponent(rbsi512)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbno512)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnmv512))))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel74)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnocum51)
                            .addComponent(lblcum51)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel73)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel72))
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbjustiitem51)
                        .addComponent(rbnojustiitem51)
                        .addComponent(noaplicaitem51))
                    .addComponent(btnadjnoitem51)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbsi511)
                        .addComponent(rbno511)
                        .addComponent(btnmv511))
                    .addComponent(jLabel74))
                .addGap(40, 40, 40)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                            .addComponent(jLabel77)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel78)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbsi513)
                                    .addComponent(rbno513)
                                    .addComponent(btnmv513))
                                .addComponent(jLabel79)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                            .addComponent(jLabel75)
                            .addGap(97, 97, 97)))
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbsi512)
                        .addComponent(rbno512)
                        .addComponent(btnmv512)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ítem 2:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 16))); // NOI18N

        jLabel70.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel70.setText("Modo de Verificación ");

        jLabel82.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel82.setText("Brigada de prevención conformada y capacitada (5%)");

        lblnocum52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Close.png"))); // NOI18N

        lblcum52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/checked.png"))); // NOI18N

        noaplicaitem52.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        noaplicaitem52.setText("No Aplica");
        noaplicaitem52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noaplicaitem52ActionPerformed(evt);
            }
        });

        rbjustiitem52.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbjustiitem52.setText("Justifica");
        rbjustiitem52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbjustiitem52ActionPerformed(evt);
            }
        });

        rbnojustiitem52.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        rbnojustiitem52.setText("No justifica");
        rbnojustiitem52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnojustiitem52ActionPerformed(evt);
            }
        });

        txtitem52.setColumns(20);
        txtitem52.setRows(5);
        txtitem52.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtitem52KeyPressed(evt);
            }
        });
        jScrollPane16.setViewportView(txtitem52);

        btnadjnoitem52.setText("Adjuntar Doc");
        btnadjnoitem52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadjnoitem52ActionPerformed(evt);
            }
        });

        jLabel83.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel83.setText("1. Solicitar el documento de conformación de la brigada de prevención, preparación y respuesta ante emergencias  y verificar los soportes ");

        rbsi521.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbsi521.setText("Cumple");
        rbsi521.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsi521ActionPerformed(evt);
            }
        });

        rbno521.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbno521.setText("No cumple");
        rbno521.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbno521ActionPerformed(evt);
            }
        });

        btnmv521.setText("Adjuntar Doc");
        btnmv521.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmv521ActionPerformed(evt);
            }
        });

        jLabel84.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N

        jLabel85.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel85.setText("de la capacitación y entrega de la dotación.");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("<<< Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save(1).png"))); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton14.setText("Criterio");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addContainerGap(55, Short.MAX_VALUE)
                        .addComponent(jLabel83)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(rbsi521)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbno521)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmv521)
                .addGap(109, 109, 109))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(531, 531, 531)
                .addComponent(jButton1)
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addGap(54, 54, 54)
                .addComponent(jLabel84)
                .addGap(18, 18, 18))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblnocum52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcum52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel82)
                            .addComponent(jButton14)))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noaplicaitem52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbjustiitem52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbnojustiitem52)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadjnoitem52, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnocum52)
                                    .addComponent(lblcum52))
                                .addGap(34, 34, 34))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addComponent(jLabel82)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton14)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel70))
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbjustiitem52)
                        .addComponent(rbnojustiitem52)
                        .addComponent(noaplicaitem52))
                    .addComponent(btnadjnoitem52)
                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbsi521)
                            .addComponent(rbno521)
                            .addComponent(btnmv521)))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel83)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel85)))
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel84)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(31, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 110, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1315, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noaplicaitem51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noaplicaitem51ActionPerformed
      
         if(noaplicaitem51.isSelected()){
        rbsi511.setEnabled(false);
        rbno511.setEnabled(false);
         rbsi512.setEnabled(false);
        rbno512.setEnabled(false);
         rbsi513.setEnabled(false);
        rbno513.setEnabled(false);
        btnmv511.setEnabled(false);
        btnmv512.setEnabled(false);
        btnmv513.setEnabled(false);
         txtitem51.setEnabled(false);
          btnadjnoitem51.setEnabled(false);
            rbjustiitem51.setEnabled(true);
          rbnojustiitem51.setEnabled(true);
          tr.setI511("");
        
        }else{
          rbsi511.setEnabled(true);
        rbno511.setEnabled(true);
         rbsi512.setEnabled(true);
        rbno512.setEnabled(true);
         rbsi513.setEnabled(true);
        rbno513.setEnabled(true);
        btnmv511.setEnabled(false);
        btnmv512.setEnabled(false);
        btnmv513.setEnabled(false);
         txtitem51.setEnabled(false);
          btnadjnoitem51.setEnabled(false);
          rbjustiitem51.setEnabled(false);
          rbnojustiitem51.setEnabled(false);  
            
            
        }
        
    }//GEN-LAST:event_noaplicaitem51ActionPerformed

    private void rbjustiitem51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbjustiitem51ActionPerformed
      txtitem51.setEnabled(true);
       tr.setI511("");
    }//GEN-LAST:event_rbjustiitem51ActionPerformed

    private void rbnojustiitem51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnojustiitem51ActionPerformed
      btnadjnoitem51.setEnabled(false);
        txtitem51.setEnabled(false);
        lblcum51.setEnabled(false);
        lblnocum51.setEnabled(true);
         tr.setI511("");
        tr.setI511("No");
        tr.setA511("");
        tr.setA511("Si");
        tr.setV511("");
        tr.setV511("No");
        tr.setV512("");
        tr.setV512("No");
        tr.setV513("");
        tr.setV513("No");
        tr.setJ511("");
    }//GEN-LAST:event_rbnojustiitem51ActionPerformed

    private void txtitem51KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitem51KeyPressed
         if(txtitem51.getText().length()>2){
       
       lblcum51.setEnabled(true);
       btnadjnoitem51.setEnabled(true);
     // inserta datos que cumple  
     
    
       tr.setI511("");
       tr.setI511("Si");
       tr.setA511("");
       tr.setA511("No");
       tr.setV511("");
       tr.setV511("no aplica");
       tr.setV512("");
       tr.setV512("no aplica");
       tr.setV513("");
       tr.setV513("no aplica");
       tr.setJ511("");
       tr.setJ511(txtitem51.getText());
       
       
   }else{
        tr.setJ511("");
            tr.setI511("");
                    
            lblcum51.setEnabled(false);
            lblnocum51.setEnabled(false);
            btnadjnoitem51.setEnabled(false);
   }
        
    }//GEN-LAST:event_txtitem51KeyPressed

    private void btnadjnoitem51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadjnoitem51ActionPerformed
        // Objeto para guardar las variables  
        Mrecursos tr= new Mrecursos();
       // objeto llamar el metodo (MVC)
        Crecursos func= new Crecursos();
        // ventanilla de carga
        JFileChooser se = new JFileChooser();
        //para que solo acepte archivos
       se.setFileSelectionMode(JFileChooser.FILES_ONLY);
       // cuadro dialogo abrir
       int estado= se.showOpenDialog(null);
       
       // Si aprueba el archivo
       
       if(estado == JFileChooser.APPROVE_OPTION){
          
           try {
               
               // mando los datos a las variables
               
               tr.setFi1111( new FileInputStream(se.getSelectedFile()));
               tr.setLongitud((int)se.getSelectedFile().length());
               tr.setId(51);
               tr.setNombre("\\" + (se.getSelectedFile().getName()));
               
               //llama el metodo
               if(func.insertarArchivos(tr)){
                         
               JOptionPane.showMessageDialog(null,"El archivo ha sido guardado exitosamente");
           }
                              
           }catch(Exception e){
               
               
           }
               
       }
    }//GEN-LAST:event_btnadjnoitem51ActionPerformed

    private void rbsi511ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsi511ActionPerformed
      tr.setV511("");
        tr.setV511("Si");
        btnmv511.setEnabled(true);
        
        if(rbsi511.isSelected() && rbsi512.isSelected() && rbsi513.isSelected()){
            lblcum51.setEnabled(true);
            lblnocum51.setEnabled(false);
        }

    }//GEN-LAST:event_rbsi511ActionPerformed

    private void rbno511ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbno511ActionPerformed
        tr.setV511("");
        tr.setV511("No");
        btnmv511.setEnabled(false);
        
        if(rbno511.isSelected() || rbno512.isSelected() || rbno513.isSelected()){
            lblcum51.setEnabled(false);
            lblnocum51.setEnabled(true);
        }
    }//GEN-LAST:event_rbno511ActionPerformed

    private void btnmv511ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmv511ActionPerformed
         // objeto para guardar la informacion de las variables (MVC)
            Mrecursos tr= new Mrecursos();  
          // objeto para llamar los metodos 
        Crecursos func= new Crecursos();
        // ventanilla de carga
        JFileChooser se = new JFileChooser();
        //para que solo acepte archivos
       se.setFileSelectionMode(JFileChooser.FILES_ONLY);
       // cuadro dialogo abrir
       int estado= se.showOpenDialog(null);
       
       // Si aprueba el archivo
       
       if(estado == JFileChooser.APPROVE_OPTION){
          
           try {
               
               // mando los datos a las variables
               
               tr.setFi1111( new FileInputStream(se.getSelectedFile()));
               tr.setLongitud((int)se.getSelectedFile().length());
               tr.setId(80);
               tr.setNombre("\\" + (se.getSelectedFile().getName()));
               
               //llama el metodo
               if(func.insertarArchivosVeri(tr)){
                 
            JOptionPane.showMessageDialog(null,"El archivo ha sido guardado exitosamente");
           }
                              
           }catch(Exception e){
               
               
           }
           
       }
    }//GEN-LAST:event_btnmv511ActionPerformed

    private void rbsi513ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsi513ActionPerformed
       tr.setV513("");
        tr.setV513("Si");
        btnmv513.setEnabled(true);
        
        if(rbsi511.isSelected() && rbsi512.isSelected() && rbsi513.isSelected()){
            lblcum51.setEnabled(true);
            lblnocum51.setEnabled(false);
        }

    }//GEN-LAST:event_rbsi513ActionPerformed

    private void rbno513ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbno513ActionPerformed
        tr.setV513("");
        tr.setV513("No");
        btnmv513.setEnabled(false);
        
        if(rbno511.isSelected() || rbno512.isSelected() || rbno513.isSelected()){
            lblcum51.setEnabled(false);
            lblnocum51.setEnabled(true);
        }
    }//GEN-LAST:event_rbno513ActionPerformed

    private void btnmv513ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmv513ActionPerformed
        // objeto para guardar la informacion de las variables (MVC)
            Mrecursos tr= new Mrecursos();  
          // objeto para llamar los metodos 
        Crecursos func= new Crecursos();
        // ventanilla de carga
        JFileChooser se = new JFileChooser();
        //para que solo acepte archivos
       se.setFileSelectionMode(JFileChooser.FILES_ONLY);
       // cuadro dialogo abrir
       int estado= se.showOpenDialog(null);
       
       // Si aprueba el archivo
       
       if(estado == JFileChooser.APPROVE_OPTION){
          
           try {
               
               // mando los datos a las variables
               
               tr.setFi1111( new FileInputStream(se.getSelectedFile()));
               tr.setLongitud((int)se.getSelectedFile().length());
               tr.setId(82);
               tr.setNombre("\\" + (se.getSelectedFile().getName()));
               
               //llama el metodo
               if(func.insertarArchivosVeri(tr)){
                 
            JOptionPane.showMessageDialog(null,"El archivo ha sido guardado exitosamente");
           }
                              
           }catch(Exception e){
               
               
           }
           
       }
    }//GEN-LAST:event_btnmv513ActionPerformed

    private void rbsi512ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsi512ActionPerformed
         tr.setV512("");
        tr.setV512("Si");
        btnmv512.setEnabled(true);
        
        if(rbsi511.isSelected() && rbsi512.isSelected() && rbsi513.isSelected()){
            lblcum51.setEnabled(true);
            lblnocum51.setEnabled(false);
        }

    }//GEN-LAST:event_rbsi512ActionPerformed

    private void rbno512ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbno512ActionPerformed
        tr.setV512("");
        tr.setV512("No");
        btnmv512.setEnabled(false);
        
        if(rbno511.isSelected() || rbno512.isSelected() || rbno513.isSelected()){
            lblcum51.setEnabled(false);
            lblnocum51.setEnabled(true);
        }
    }//GEN-LAST:event_rbno512ActionPerformed

    private void btnmv512ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmv512ActionPerformed
          // objeto para guardar la informacion de las variables (MVC)
            Mrecursos tr= new Mrecursos();  
          // objeto para llamar los metodos 
        Crecursos func= new Crecursos();
        // ventanilla de carga
        JFileChooser se = new JFileChooser();
        //para que solo acepte archivos
       se.setFileSelectionMode(JFileChooser.FILES_ONLY);
       // cuadro dialogo abrir
       int estado= se.showOpenDialog(null);
       
       // Si aprueba el archivo
       
       if(estado == JFileChooser.APPROVE_OPTION){
          
           try {
               
               // mando los datos a las variables
               
               tr.setFi1111( new FileInputStream(se.getSelectedFile()));
               tr.setLongitud((int)se.getSelectedFile().length());
               tr.setId(81);
               tr.setNombre("\\" + (se.getSelectedFile().getName()));
               
               //llama el metodo
               if(func.insertarArchivosVeri(tr)){
                 
            JOptionPane.showMessageDialog(null,"El archivo ha sido guardado exitosamente");
           }
                              
           }catch(Exception e){
               
               
           }
           
       }
    }//GEN-LAST:event_btnmv512ActionPerformed

    private void noaplicaitem52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noaplicaitem52ActionPerformed
    
        if(noaplicaitem52.isSelected()){
        rbsi521.setEnabled(false);
        rbno521.setEnabled(false);
        btnmv521.setEnabled(false);
        txtitem52.setEnabled(false);
        btnadjnoitem52.setEnabled(false);
          rbjustiitem52.setEnabled(true);
          rbnojustiitem52.setEnabled(true);
          tr.setI521("");
        
        }else{
          rbsi521.setEnabled(true);
        rbno521.setEnabled(true);
        btnmv521.setEnabled(false);
       txtitem52.setEnabled(false);
        btnadjnoitem52.setEnabled(false);
          rbjustiitem52.setEnabled(false);
          rbnojustiitem52.setEnabled(false);
            
            
        }  
    }//GEN-LAST:event_noaplicaitem52ActionPerformed

    private void rbjustiitem52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbjustiitem52ActionPerformed
       txtitem52.setEnabled(true);
       tr.setI521("");
    }//GEN-LAST:event_rbjustiitem52ActionPerformed

    private void rbnojustiitem52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnojustiitem52ActionPerformed
       btnadjnoitem52.setEnabled(false);
        txtitem52.setEnabled(false);
        lblcum52.setEnabled(false);
        lblnocum52.setEnabled(true);
         tr.setI521("");
        tr.setI521("No");
        tr.setA521("");
        tr.setA521("Si");
        tr.setV521("");
        tr.setV521("No");
        tr.setJ521("");

    }//GEN-LAST:event_rbnojustiitem52ActionPerformed

    private void txtitem52KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitem52KeyPressed
      if(txtitem52.getText().length()>2){        
        lblcum52.setEnabled(true);
       btnadjnoitem52.setEnabled(true);
     // inserta datos que cumple  
       tr.setI521("");
       tr.setI521("Si");
       tr.setA521("");
       tr.setA521("No");
       tr.setV521("");
       tr.setV521("no aplica");
       tr.setJ521("");
       tr.setJ521(txtitem52.getText());
       
       
   }else{
        tr.setJ521("");
        tr.setI521("");
           
            lblcum52.setEnabled(false);
            lblnocum52.setEnabled(false);
            btnadjnoitem52.setEnabled(false);
   }
    }//GEN-LAST:event_txtitem52KeyPressed

    private void btnadjnoitem52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadjnoitem52ActionPerformed
       // Objeto para guardar las variables  
        Mrecursos tr= new Mrecursos();
       // objeto llamar el metodo (MVC)
        Crecursos func= new Crecursos();
        // ventanilla de carga
        JFileChooser se = new JFileChooser();
        //para que solo acepte archivos
       se.setFileSelectionMode(JFileChooser.FILES_ONLY);
       // cuadro dialogo abrir
       int estado= se.showOpenDialog(null);
       
       // Si aprueba el archivo
       
       if(estado == JFileChooser.APPROVE_OPTION){
          
           try {
               
               // mando los datos a las variables
               
               tr.setFi1111( new FileInputStream(se.getSelectedFile()));
               tr.setLongitud((int)se.getSelectedFile().length());
               tr.setId(52);
               tr.setNombre("\\" + (se.getSelectedFile().getName()));
               
               //llama el metodo
               if(func.insertarArchivos(tr)){
                         
               JOptionPane.showMessageDialog(null,"El archivo ha sido guardado exitosamente");
           }
                              
           }catch(Exception e){
               
               
           }
               
       }
    }//GEN-LAST:event_btnadjnoitem52ActionPerformed

    private void rbsi521ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsi521ActionPerformed
       tr.setV521("");
 tr.setV521("Si");
 btnmv521.setEnabled(true);
        
        if(rbsi521.isSelected()){
            lblcum52.setEnabled(true);
            lblnocum52.setEnabled(false);
        }

    }//GEN-LAST:event_rbsi521ActionPerformed

    private void rbno521ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbno521ActionPerformed
      tr.setV521("");
      tr.setV521("No");
      btnmv521.setEnabled(false);
        
        if(rbno521.isSelected()){
            lblcum52.setEnabled(false);
            lblnocum52.setEnabled(true);
        }
    }//GEN-LAST:event_rbno521ActionPerformed

    private void btnmv521ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmv521ActionPerformed
        // objeto para guardar la informacion de las variables (MVC)
            Mrecursos tr= new Mrecursos();  
          // objeto para llamar los metodos 
        Crecursos func= new Crecursos();
        // ventanilla de carga
        JFileChooser se = new JFileChooser();
        //para que solo acepte archivos
       se.setFileSelectionMode(JFileChooser.FILES_ONLY);
       // cuadro dialogo abrir
       int estado= se.showOpenDialog(null);
       
       // Si aprueba el archivo
       
       if(estado == JFileChooser.APPROVE_OPTION){
          
           try {
               
               // mando los datos a las variables
               
               tr.setFi1111( new FileInputStream(se.getSelectedFile()));
               tr.setLongitud((int)se.getSelectedFile().length());
               tr.setId(83);
               tr.setNombre("\\" + (se.getSelectedFile().getName()));
               
               //llama el metodo
               if(func.insertarArchivosVeri(tr)){
                 
            JOptionPane.showMessageDialog(null,"El archivo ha sido guardado exitosamente");
           }
                              
           }catch(Exception e){
               
               
           }
           
       }
    }//GEN-LAST:event_btnmv521ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
gh.setVisible(true);
gh.toFront();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // Item 51
        if(rbsi511.isSelected() && rbsi512.isSelected() && rbsi513.isSelected()){
            tr.setI511("");
            tr.setI511("si");
            tr.setA511("");
            tr.setA511("si");

        }
        if(rbno511.isSelected() || rbno512.isSelected() || rbno513.isSelected()){
          if((!rbno511.isSelected() && !rbsi511.isSelected()) || (!rbno512.isSelected() && !rbsi512.isSelected()) || (!rbno513.isSelected() && !rbsi513.isSelected()) 
       ){   
                
        }else{  
            
            tr.setI511("");
            tr.setI511("no");
            tr.setA511("");
            tr.setA511("si"); }

        }
        // Item 2

        if(rbsi521.isSelected()){
            tr.setI521("");
            tr.setI521("si");
            tr.setA521("");
            tr.setA521("si");

        }

        if(rbno521.isSelected()){
            tr.setI521("");
            tr.setI521("no");
            tr.setA521("");
            tr.setA521("si");

        }

       Validar();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        }catch(Exception e){
            
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_amenazas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadjnoitem51;
    private javax.swing.JButton btnadjnoitem52;
    private javax.swing.JButton btnmv511;
    private javax.swing.JButton btnmv512;
    private javax.swing.JButton btnmv513;
    private javax.swing.JButton btnmv521;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JLabel lblcum51;
    private javax.swing.JLabel lblcum52;
    private javax.swing.JLabel lblnocum51;
    private javax.swing.JLabel lblnocum52;
    private javax.swing.JCheckBox noaplicaitem51;
    private javax.swing.JCheckBox noaplicaitem52;
    private javax.swing.JRadioButton rbjustiitem51;
    private javax.swing.JRadioButton rbjustiitem52;
    private javax.swing.JRadioButton rbno511;
    private javax.swing.JRadioButton rbno512;
    private javax.swing.JRadioButton rbno513;
    private javax.swing.JRadioButton rbno521;
    private javax.swing.JRadioButton rbnojustiitem51;
    private javax.swing.JRadioButton rbnojustiitem52;
    private javax.swing.JRadioButton rbsi511;
    private javax.swing.JRadioButton rbsi512;
    private javax.swing.JRadioButton rbsi513;
    private javax.swing.JRadioButton rbsi521;
    private javax.swing.JTextArea txtitem51;
    private javax.swing.JTextArea txtitem52;
    // End of variables declaration//GEN-END:variables
}
