/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.C_ArchivoEncuesta;
import Controlador.C_DesHabEncu;
import Controlador.C_HabEncuTodos;
import Controlador.C_IngresoSistema;
import static Controlador.C_IngresoSistema.user;
import Controlador.C_RealizarEncuesta;
import Controlador.C_RegistrarEmpleado;
import Modelo.ArchivoEncuesta;
import Modelo.Conexion;
import Modelo.M_DesHabEncuesta;
import Modelo.M_EncuestaSocioDemografica;
import Modelo.M_HabEncuTodos;
import Modelo.M_IngresoSistema;
import Modelo.M_RegistrarEmpleado;
import Modelo.infoEmpEncuesta;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author leandro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    boolean perfil,acerca,ayuda;
    
Llamados_Atencion vista_llamadosAtencion;
private Connection connection= new Conexion().getConexion();
    public Principal() {
        initComponents();
        transparenciaCerrar (); 
        this.setExtendedState(MAXIMIZED_BOTH);
        perfil = acerca = ayuda = false;
        
        ImageIcon fondo=new ImageIcon(getClass().getResource("/imagenes/PRINCIPAL3.jpg"));
        ImageIcon adapFondo=new ImageIcon(fondo.getImage().getScaledInstance(label_fondo.getWidth(), label_fondo.getHeight(), Image.SCALE_DEFAULT));
        label_fondo.setIcon(adapFondo);
       panel_perfil.setVisible(false);
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    @SuppressWarnings("unchecked")
    public void transparenciaCerrar (){
        Btn_Cerrar.setOpaque(false);
        Btn_Cerrar.setContentAreaFilled(false);
        Btn_Cerrar.setBorderPainted(false);
        
      //  btnAcerca.setOpaque(false);
       // btnAcerca.setContentAreaFilled(false);
       // btnAcerca.setBorderPainted(false);
        

    }
    
    public void panelPrimero (){
      panel_perfil.setVisible(false);
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btn_perfil = new javax.swing.JButton();
        btn_acerca = new javax.swing.JButton();
        btn_ayuda = new javax.swing.JButton();
        panel_perfil = new javax.swing.JPanel();
        Btn_Cerrar = new javax.swing.JButton();
        txt_nombrePerfil = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_PrimerApellido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txt_Nombres = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        btnEditar_Perfil = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        label_rol = new javax.swing.JLabel();
        label_nombreUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        label_fondo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jm_realizarEvaIni = new javax.swing.JMenu();
        jm_realizarEvaluacion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jm_RealizarEncuesta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jm_habEncu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        me_registrarEmpleado = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jm_evaluacionIni = new javax.swing.JMenu();
        mn_items_cumple = new javax.swing.JMenuItem();
        mn_itemnoCumple = new javax.swing.JMenuItem();
        mn_veriCumple = new javax.swing.JMenuItem();
        mn_criteriosNoCumple = new javax.swing.JMenuItem();
        mn_noaplica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jm_realizarLlamadoAtencion = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1079, 705));
        setResizable(false);

        desktopPane.setBackground(new java.awt.Color(255, 51, 0));
        desktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        desktopPane.setForeground(new java.awt.Color(204, 102, 0));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo 132.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(1180, 0, 140, 150);

        btn_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        btn_perfil.setBorder(null);
        btn_perfil.setBorderPainted(false);
        btn_perfil.setContentAreaFilled(false);
        btn_perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_perfil.setFocusPainted(false);
        btn_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_perfilMouseExited(evt);
            }
        });
        btn_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perfilActionPerformed(evt);
            }
        });
        jPanel1.add(btn_perfil);
        btn_perfil.setBounds(-175, 10, 229, 61);

        btn_acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acerca.png"))); // NOI18N
        btn_acerca.setBorder(null);
        btn_acerca.setBorderPainted(false);
        btn_acerca.setContentAreaFilled(false);
        btn_acerca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_acerca.setFocusPainted(false);
        btn_acerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_acercaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_acercaMouseExited(evt);
            }
        });
        btn_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acercaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_acerca);
        btn_acerca.setBounds(-175, 80, 229, 61);

        btn_ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda_1.png"))); // NOI18N
        btn_ayuda.setBorder(null);
        btn_ayuda.setBorderPainted(false);
        btn_ayuda.setContentAreaFilled(false);
        btn_ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ayuda.setFocusPainted(false);
        btn_ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ayudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ayudaMouseExited(evt);
            }
        });
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ayuda);
        btn_ayuda.setBounds(-175, 150, 229, 61);

        panel_perfil.setBackground(new java.awt.Color(252, 100, 50));

        Btn_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CerrarActionPerformed(evt);
            }
        });

        txt_nombrePerfil.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        txt_nombrePerfil.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombrePerfil.setText("PERFIL ");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Segundo Apellido:");

        txt_PrimerApellido.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txt_PrimerApellido.setForeground(new java.awt.Color(0, 0, 0));
        txt_PrimerApellido.setText("Primer Apellido:");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Numero de Documento:");

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tipo de Documento:");

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Coreo Eectronico:");

        jTextField1.setEditable(false);

        txt_Nombres.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txt_Nombres.setForeground(new java.awt.Color(0, 0, 0));
        txt_Nombres.setText("Nombres:");

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Telefono:");

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Area:");

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Genero:");

        jTextField4.setEditable(false);

        jTextField5.setEditable(false);

        jTextField6.setEditable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setEditable(false);

        jTextField8.setEditable(false);

        jTextField9.setEditable(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        btnEditar_Perfil.setText("Editar Perfil");

        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout panel_perfilLayout = new javax.swing.GroupLayout(panel_perfil);
        panel_perfil.setLayout(panel_perfilLayout);
        panel_perfilLayout.setHorizontalGroup(
            panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_perfilLayout.createSequentialGroup()
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_perfilLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_PrimerApellido)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Nombres))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addGroup(panel_perfilLayout.createSequentialGroup()
                                .addComponent(btnEditar_Perfil)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar))
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(panel_perfilLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nombrePerfil)
                        .addGap(188, 188, 188)
                        .addComponent(Btn_Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_perfilLayout.setVerticalGroup(
            panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_perfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Cerrar)
                    .addComponent(txt_nombrePerfil))
                .addGap(58, 58, 58)
                .addComponent(txt_Nombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_PrimerApellido)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(panel_perfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar_Perfil)
                    .addComponent(btnGuardar))
                .addGap(20, 20, 20))
        );

        jPanel1.add(panel_perfil);
        panel_perfil.setBounds(60, 10, 590, 530);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/safety transparente.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(670, 20, 520, 120);

        label_rol.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        label_rol.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(label_rol);
        label_rol.setBounds(1130, 180, 210, 30);

        label_nombreUser.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        label_nombreUser.setForeground(new java.awt.Color(0, 0, 0));
        label_nombreUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nombreUser.setText("User");
        jPanel1.add(label_nombreUser);
        label_nombreUser.setBounds(1080, 150, 260, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn primero.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1030, 200, 200, 200);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn segundo.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(600, 190, 200, 210);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn tercero.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(190, 190, 220, 200);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn cuarto.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(370, 390, 210, 210);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn quinto.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(800, 400, 210, 210);
        jPanel1.add(label_fondo);
        label_fondo.setBounds(0, 0, 1360, 680);

        desktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1369, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        jm_realizarEvaIni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notebook.png"))); // NOI18N
        jm_realizarEvaIni.setMnemonic('f');
        jm_realizarEvaIni.setText("Evaluacion Inicial");
        jm_realizarEvaIni.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jm_realizarEvaluacion.setMnemonic('o');
        jm_realizarEvaluacion.setText("Realizar Evaluacion Inicial");
        jm_realizarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_realizarEvaluacionActionPerformed(evt);
            }
        });
        jm_realizarEvaIni.add(jm_realizarEvaluacion);

        menuBar.add(jm_realizarEvaIni);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DIAGRAMA.png"))); // NOI18N
        jMenu3.setText("Perfil Socio-demografico");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenu3.add(jSeparator1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/encuesta 1.2.png"))); // NOI18N
        jMenu5.setText("Encuesta SocioDemografica");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jm_RealizarEncuesta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jm_RealizarEncuesta.setText("Realizar Encuesta");
        jm_RealizarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_RealizarEncuestaActionPerformed(evt);
            }
        });
        jMenu5.add(jm_RealizarEncuesta);

        jMenu3.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo 2.png"))); // NOI18N
        jMenu4.setText("Administrar Encuestas");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem9.setText("Ver Encuestas Realizadas");
        jMenu4.add(jMenuItem9);

        jMenuItem2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem2.setText("Deshabilitar Encuesta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jm_habEncu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jm_habEncu.setText("Habilitar Encuesta");
        jm_habEncu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_habEncuActionPerformed(evt);
            }
        });
        jMenu4.add(jm_habEncu);

        jMenu3.add(jMenu4);

        menuBar.add(jMenu3);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EMPLEADOS.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Empleados");
        editMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        me_registrarEmpleado.setMnemonic('t');
        me_registrarEmpleado.setText("Registrar Empleado");
        me_registrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                me_registrarEmpleadoActionPerformed(evt);
            }
        });
        editMenu.add(me_registrarEmpleado);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/REPORTES.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Reportes");
        helpMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jm_evaluacionIni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newspaper(1).png"))); // NOI18N
        jm_evaluacionIni.setText("Evaluacion Inicial");

        mn_items_cumple.setText("Estado de La Empresa (Items que Cumple)");
        mn_items_cumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_items_cumpleActionPerformed(evt);
            }
        });
        jm_evaluacionIni.add(mn_items_cumple);

        mn_itemnoCumple.setText("Por Alcanzar (Items que no Cumple)");
        mn_itemnoCumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_itemnoCumpleActionPerformed(evt);
            }
        });
        jm_evaluacionIni.add(mn_itemnoCumple);

        mn_veriCumple.setText("Documentacion y criterios (Verificaciones que cumplen)");
        mn_veriCumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_veriCumpleActionPerformed(evt);
            }
        });
        jm_evaluacionIni.add(mn_veriCumple);

        mn_criteriosNoCumple.setText("Documentacion y criterios por Alcanzar");
        mn_criteriosNoCumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_criteriosNoCumpleActionPerformed(evt);
            }
        });
        jm_evaluacionIni.add(mn_criteriosNoCumple);

        mn_noaplica.setText("Items que la Empresa No Aplica");
        jm_evaluacionIni.add(mn_noaplica);

        helpMenu.add(jm_evaluacionIni);

        menuBar.add(helpMenu);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ATENCION.png"))); // NOI18N
        jMenu2.setText("Llamados de atencion");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jm_realizarLlamadoAtencion.setText("Realizar Llamado de Atencion");
        jm_realizarLlamadoAtencion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_realizarLlamadoAtencionMouseClicked(evt);
            }
        });
        jMenu2.add(jm_realizarLlamadoAtencion);

        menuBar.add(jMenu2);

        jmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.png"))); // NOI18N
        jmSalir.setText("Salir");
        jmSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        menuBar.add(jmSalir);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void btn_ayudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ayudaMouseExited
        // TODO add your handling code here:
        if (!ayuda)
            Animacion.Animacion.mover_izquierda(0, -178, 1, 2, btn_ayuda);
    }//GEN-LAST:event_btn_ayudaMouseExited

    private void btn_ayudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ayudaMouseEntered
        // TODO add your handling code here:
        if(!ayuda)
        Animacion.Animacion.mover_derecha(-178, 0, 1, 2, btn_ayuda);
    }//GEN-LAST:event_btn_ayudaMouseEntered

    private void btn_acercaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acercaMouseExited
        // TODO add your handling code here:
        if (!acerca)
        Animacion.Animacion.mover_izquierda(0, -178, 1, 2, btn_acerca);
    }//GEN-LAST:event_btn_acercaMouseExited

    private void btn_acercaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acercaMouseEntered
        // TODO add your handling code here:
        if(!acerca)
        Animacion.Animacion.mover_derecha(-178, 0, 1, 2, btn_acerca);
    }//GEN-LAST:event_btn_acercaMouseEntered

    private void btn_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perfilActionPerformed
       panel_perfil.setVisible(true);
     // Panel_Acerca.setVisible(false);
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_perfilActionPerformed

    private void btn_perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perfilMouseExited
        // TODO add your handling code here:
        if (!perfil)
        Animacion.Animacion.mover_izquierda(0, -178, 1, 2, btn_perfil);
    }//GEN-LAST:event_btn_perfilMouseExited

    private void btn_perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perfilMouseEntered
        // TODO add your handling code here:
        if(!perfil)
        Animacion.Animacion.mover_derecha(-178, 0, 1, 2, btn_perfil);
    }//GEN-LAST:event_btn_perfilMouseEntered

    private void jm_RealizarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_RealizarEncuestaActionPerformed
        
       Encuesta_SocioDemografica realizarEncuesta=new Encuesta_SocioDemografica();
       M_EncuestaSocioDemografica modelo_encuesta=new M_EncuestaSocioDemografica();
          
       C_RealizarEncuesta controlador_realizarEncuesta=new C_RealizarEncuesta(realizarEncuesta, modelo_encuesta);
        
       realizarEncuesta.setVisible(true);
    }//GEN-LAST:event_jm_RealizarEncuestaActionPerformed

    private void Btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CerrarActionPerformed
panel_perfil.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_Btn_CerrarActionPerformed

   
    
    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
    
        int opcionSalir = JOptionPane.showConfirmDialog(null,"Esta seguro que desea salir.");
        if (JOptionPane.YES_OPTION == opcionSalir){
           System.exit(0); 
        }
        
    }//GEN-LAST:event_jmSalirMouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void btn_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acercaActionPerformed
        
        panel_perfil.setVisible(false);
     //  Panel_Acerca.setVisible(true);
        
        
      
        
        
        

// TODO add your handling code here:
    }//GEN-LAST:event_btn_acercaActionPerformed

    private void jm_realizarLlamadoAtencionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_realizarLlamadoAtencionMouseClicked
      vista_llamadosAtencion=new Llamados_Atencion();
        vista_llamadosAtencion.setVisible(true);
    }//GEN-LAST:event_jm_realizarLlamadoAtencionMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DeshabEncuesta vista=new DeshabEncuesta();
        M_DesHabEncuesta modelo=new M_DesHabEncuesta();
        C_DesHabEncu controlador=new C_DesHabEncu(vista,modelo);
        vista.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mn_items_cumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_items_cumpleActionPerformed
         Map p= new HashMap();
        JasperReport repor;
        JasperPrint print;
        
        try {
            repor= JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpnocumveri.jrxml");
            print= JasperFillManager.fillReport(repor, p,connection);
           JasperViewer view= new JasperViewer(print, false);
            view.setTitle("Reporte de la documentacion y criterios que no cumple la empresa");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mn_items_cumpleActionPerformed

    private void mn_itemnoCumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_itemnoCumpleActionPerformed
        Map p= new HashMap();
        JasperReport repor;
        JasperPrint print;
        
        try {
            repor= JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpnocumitem.jrxml");
            print= JasperFillManager.fillReport(repor, p,connection);
           JasperViewer view= new JasperViewer(print, false);
            view.setTitle("Reporte de la documentacion y criterios que cumple la empresa");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mn_itemnoCumpleActionPerformed

    private void mn_veriCumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_veriCumpleActionPerformed
        Map p= new HashMap();
        JasperReport repor;
        JasperPrint print;
        
        try {
            repor= JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpcumveri.jrxml");
            print= JasperFillManager.fillReport(repor, p,connection);
           JasperViewer view= new JasperViewer(print, false);
            view.setTitle("Reporte de la documentacion y criterios que cumple la empresa");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mn_veriCumpleActionPerformed

    private void mn_criteriosNoCumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_criteriosNoCumpleActionPerformed
         Map p= new HashMap();
        JasperReport repor;
        JasperPrint print;
        
        try {
            repor= JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpnocumveri.jrxml");
            print= JasperFillManager.fillReport(repor, p,connection);
           JasperViewer view= new JasperViewer(print, false);
            view.setTitle("Reporte de la documentacion y criterios que no cumple la empresa");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mn_criteriosNoCumpleActionPerformed

    private void me_registrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_me_registrarEmpleadoActionPerformed
         RegistroEmpleados vista=new RegistroEmpleados();
                M_RegistrarEmpleado modelo=new M_RegistrarEmpleado();
                C_RegistrarEmpleado controlador=new C_RegistrarEmpleado(vista,modelo);
                
                vista.setVisible(true);
    }//GEN-LAST:event_me_registrarEmpleadoActionPerformed

    private void jm_realizarEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_realizarEvaluacionActionPerformed
        Evaluacion_Ini vista_evaluacion=new Evaluacion_Ini();
        vista_evaluacion.toFront();
        vista_evaluacion.setVisible(true);
    }//GEN-LAST:event_jm_realizarEvaluacionActionPerformed

    private void jm_habEncuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_habEncuActionPerformed
        HabEncuestaTodos vista_habEncuTodos=new HabEncuestaTodos();
        M_HabEncuTodos modelo_habEncuTodos= new M_HabEncuTodos();
        C_HabEncuTodos controlador_habEncuTodos=new C_HabEncuTodos(vista_habEncuTodos, modelo_habEncuTodos);
             vista_habEncuTodos.setVisible(true);
    }//GEN-LAST:event_jm_habEncuActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try{
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        }catch(Exception e){
            
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cerrar;
    private javax.swing.JButton btnEditar_Perfil;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btn_acerca;
    private javax.swing.JButton btn_ayuda;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jm_RealizarEncuesta;
    private javax.swing.JMenu jm_evaluacionIni;
    private javax.swing.JMenuItem jm_habEncu;
    public javax.swing.JMenu jm_realizarEvaIni;
    public javax.swing.JMenuItem jm_realizarEvaluacion;
    private javax.swing.JMenu jm_realizarLlamadoAtencion;
    private javax.swing.JLabel label_fondo;
    public javax.swing.JLabel label_nombreUser;
    public javax.swing.JLabel label_rol;
    private javax.swing.JMenuItem me_registrarEmpleado;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mn_criteriosNoCumple;
    private javax.swing.JMenuItem mn_itemnoCumple;
    private javax.swing.JMenuItem mn_items_cumple;
    private javax.swing.JMenuItem mn_noaplica;
    private javax.swing.JMenuItem mn_veriCumple;
    private javax.swing.JPanel panel_perfil;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JLabel txt_Nombres;
    private javax.swing.JLabel txt_PrimerApellido;
    private javax.swing.JLabel txt_nombrePerfil;
    // End of variables declaration//GEN-END:variables

  

}
