/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.C_ArchivoEncuesta;
import Controlador.C_DesHabEncu;
import Controlador.C_HabEncuTodos;
import Controlador.C_IngresoSistema;
import static Controlador.C_IngresoSistema.user;
import Controlador.C_RealizarEncuesta;
import Controlador.C_RegistrarEmpleado;
import Modelo.ArchivoEncuesta;
import Modelo.Conexion;
import Modelo.M_DesHabEncuesta;
import Modelo.M_EncuestaSocioDemografica;
import Modelo.M_HabEncuTodos;
import Modelo.M_IngresoSistema;
import Modelo.M_RegistrarEmpleado;
import Modelo.infoEmpEncuesta;
import Vista.DeshabEncuesta;
import Vista.Encuesta_SocioDemografica;
import Vista.Evaluacion_Ini;
import Vista.HabEncuestaTodos;
import Vista.Llamados_Atencion;
import Vista.RegistroEmpleados;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author leandro
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    boolean perfil,acerca,ayuda;
    
Llamados_Atencion vista_llamadosAtencion;
private Connection connection= new Conexion().getConexion();
    public Principal() {
        initComponents();
        btn_evaluacion.setVisible(false);
        btn_primero.setVisible(true);
        btn_relleno2.setVisible(false);
        btn_segundo.setVisible(true);
        btn_relleno3.setVisible(false);
        btn_tercero.setVisible(true);
        btn_regEmple.setVisible(false);
        btn_cuarto.setVisible(true);
        btn_rencu.setVisible(false);
        btn_quinto.setVisible(true);
        
        
        transparenciaCerrar (); 
        this.setExtendedState(MAXIMIZED_BOTH);
        perfil = acerca = ayuda = false;
        
        ImageIcon fondo=new ImageIcon(getClass().getResource("/imagenes/PRINCIPAL3.jpg"));
        ImageIcon adapFondo=new ImageIcon(fondo.getImage().getScaledInstance(label_fondo.getWidth(), label_fondo.getHeight(), Image.SCALE_DEFAULT));
        label_fondo.setIcon(adapFondo);
       panel_perfil.setVisible(false);
      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    
    
    @SuppressWarnings("unchecked")
    public void transparenciaCerrar (){
        Btn_Cerrar.setOpaque(false);
        Btn_Cerrar.setContentAreaFilled(false);
        Btn_Cerrar.setBorderPainted(false);
        
      //  btnAcerca.setOpaque(false);
       // btnAcerca.setContentAreaFilled(false);
       // btnAcerca.setBorderPainted(false);
        

    }
    
    public void panelPrimero (){
      panel_perfil.setVisible(false);
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btn_perfil = new javax.swing.JButton();
        btn_acerca = new javax.swing.JButton();
        btn_ayuda = new javax.swing.JButton();
        panel_perfil = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_PrimerApellido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_nombrePri = new javax.swing.JTextField();
        txt_Nombres = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        btnEditar_Perfil = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        Btn_Cerrar = new javax.swing.JButton();
        txt_nombrePerfil = new javax.swing.JLabel();
        lbl_fondoPerfil = new javax.swing.JLabel();
        label_rol = new javax.swing.JLabel();
        label_nombreUser = new javax.swing.JLabel();
        btn_relleno2 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        lbl_safetyNom = new javax.swing.JLabel();
        btn_relleno3 = new javax.swing.JLabel();
        btn_evaluacion = new javax.swing.JLabel();
        btn_primero = new javax.swing.JLabel();
        btn_tercero = new javax.swing.JLabel();
        btn_segundo = new javax.swing.JLabel();
        btn_regEmple = new javax.swing.JLabel();
        btn_cuarto = new javax.swing.JLabel();
        btn_rencu = new javax.swing.JLabel();
        btn_quinto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        label_fondo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jm_realizarEvaIni = new javax.swing.JMenu();
        jm_realizarEvaluacion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jm_RealizarEncuesta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        me_registrarEmpleado = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jm_evaluacionIni = new javax.swing.JMenu();
        mn_items_cumple = new javax.swing.JMenuItem();
        mn_itemnoCumple = new javax.swing.JMenuItem();
        mn_veriCumple = new javax.swing.JMenuItem();
        mn_criteriosNoCumple = new javax.swing.JMenuItem();
        mn_noaplica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jm_realizarLlamadoAtencion = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jm_registrarEmpresa = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1079, 705));
        setResizable(false);

        desktopPane.setBackground(new java.awt.Color(255, 51, 0));
        desktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        desktopPane.setForeground(new java.awt.Color(204, 102, 0));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setLayout(null);

        btn_perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        btn_perfil.setBorder(null);
        btn_perfil.setBorderPainted(false);
        btn_perfil.setContentAreaFilled(false);
        btn_perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_perfil.setFocusPainted(false);
        btn_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_perfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_perfilMouseExited(evt);
            }
        });
        btn_perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_perfilActionPerformed(evt);
            }
        });
        jPanel1.add(btn_perfil);
        btn_perfil.setBounds(-175, 10, 229, 61);

        btn_acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acerca.png"))); // NOI18N
        btn_acerca.setBorder(null);
        btn_acerca.setBorderPainted(false);
        btn_acerca.setContentAreaFilled(false);
        btn_acerca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_acerca.setFocusPainted(false);
        btn_acerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_acercaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_acercaMouseExited(evt);
            }
        });
        btn_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acercaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_acerca);
        btn_acerca.setBounds(-175, 80, 229, 61);

        btn_ayuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ayuda_1.png"))); // NOI18N
        btn_ayuda.setBorder(null);
        btn_ayuda.setBorderPainted(false);
        btn_ayuda.setContentAreaFilled(false);
        btn_ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ayuda.setFocusPainted(false);
        btn_ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ayudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ayudaMouseExited(evt);
            }
        });
        btn_ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayudaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ayuda);
        btn_ayuda.setBounds(-175, 150, 229, 61);

        panel_perfil.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Segundo Apellido:");
        panel_perfil.add(jLabel3);
        jLabel3.setBounds(312, 187, 153, 21);

        txt_PrimerApellido.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txt_PrimerApellido.setText("Primer Apellido:");
        panel_perfil.add(txt_PrimerApellido);
        txt_PrimerApellido.setBounds(22, 187, 138, 21);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Numero de Documento:");
        panel_perfil.add(jLabel5);
        jLabel5.setBounds(312, 256, 197, 21);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("Tipo de Documento:");
        panel_perfil.add(jLabel6);
        jLabel6.setBounds(22, 256, 169, 21);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Coreo Eectronico:");
        panel_perfil.add(jLabel9);
        jLabel9.setBounds(310, 390, 152, 21);

        txt_nombrePri.setEditable(false);
        txt_nombrePri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombrePriActionPerformed(evt);
            }
        });
        panel_perfil.add(txt_nombrePri);
        txt_nombrePri.setBounds(22, 145, 177, 30);

        txt_Nombres.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        txt_Nombres.setText("Nombres:");
        panel_perfil.add(txt_Nombres);
        txt_Nombres.setBounds(22, 118, 81, 21);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Telefono:");
        panel_perfil.add(jLabel8);
        jLabel8.setBounds(312, 325, 79, 21);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setText("Area:");
        panel_perfil.add(jLabel10);
        jLabel10.setBounds(22, 400, 45, 21);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panel_perfil.add(jTextField2);
        jTextField2.setBounds(22, 214, 177, 19);

        jTextField3.setEditable(false);
        panel_perfil.add(jTextField3);
        jTextField3.setBounds(22, 283, 177, 19);

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("Genero:");
        panel_perfil.add(jLabel2);
        jLabel2.setBounds(22, 325, 66, 21);

        jTextField4.setEditable(false);
        panel_perfil.add(jTextField4);
        jTextField4.setBounds(312, 214, 177, 19);

        jTextField5.setEditable(false);
        panel_perfil.add(jTextField5);
        jTextField5.setBounds(22, 358, 177, 19);

        jTextField6.setEditable(false);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panel_perfil.add(jTextField6);
        jTextField6.setBounds(312, 358, 177, 19);

        jTextField7.setEditable(false);
        panel_perfil.add(jTextField7);
        jTextField7.setBounds(312, 283, 177, 19);

        jTextField8.setEditable(false);
        panel_perfil.add(jTextField8);
        jTextField8.setBounds(22, 439, 177, 19);

        jTextField9.setEditable(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        panel_perfil.add(jTextField9);
        jTextField9.setBounds(310, 420, 216, 19);

        btnEditar_Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnEditar_Perfil.setText("Editar Perfil");
        btnEditar_Perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_perfil.add(btnEditar_Perfil);
        btnEditar_Perfil.setBounds(230, 460, 140, 40);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panel_perfil.add(btnGuardar);
        btnGuardar.setBounds(390, 460, 126, 40);

        Btn_Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar.png"))); // NOI18N
        Btn_Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CerrarActionPerformed(evt);
            }
        });
        panel_perfil.add(Btn_Cerrar);
        Btn_Cerrar.setBounds(500, 10, 36, 34);

        txt_nombrePerfil.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        txt_nombrePerfil.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombrePerfil.setText("PERFIL ");
        panel_perfil.add(txt_nombrePerfil);
        txt_nombrePerfil.setBounds(210, 10, 166, 50);

        lbl_fondoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil2.png"))); // NOI18N
        panel_perfil.add(lbl_fondoPerfil);
        lbl_fondoPerfil.setBounds(-10, -10, 560, 530);

        jPanel1.add(panel_perfil);
        panel_perfil.setBounds(60, 10, 550, 520);

        label_rol.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jPanel1.add(label_rol);
        label_rol.setBounds(1130, 180, 210, 30);

        label_nombreUser.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        label_nombreUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_nombreUser.setText("User");
        jPanel1.add(label_nombreUser);
        label_nombreUser.setBounds(1080, 150, 260, 30);

        btn_relleno2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/relleno segundo.png"))); // NOI18N
        btn_relleno2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_relleno2);
        btn_relleno2.setBounds(600, 200, 200, 190);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo 132.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(1190, 10, 140, 150);

        lbl_safetyNom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/safety transparente.png"))); // NOI18N
        jPanel1.add(lbl_safetyNom);
        lbl_safetyNom.setBounds(680, 30, 520, 120);

        btn_relleno3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/relleno primero.png"))); // NOI18N
        btn_relleno3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_relleno3);
        btn_relleno3.setBounds(1030, 200, 200, 200);

        btn_evaluacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/relleno tercero.png"))); // NOI18N
        btn_evaluacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_evaluacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_evaluacionMouseClicked(evt);
            }
        });
        jPanel1.add(btn_evaluacion);
        btn_evaluacion.setBounds(190, 190, 210, 200);

        btn_primero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn tercero.png"))); // NOI18N
        btn_primero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_primeroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_primeroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_primeroMouseExited(evt);
            }
        });
        jPanel1.add(btn_primero);
        btn_primero.setBounds(190, 190, 220, 200);

        btn_tercero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn primero.png"))); // NOI18N
        btn_tercero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_terceroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_terceroMouseExited(evt);
            }
        });
        jPanel1.add(btn_tercero);
        btn_tercero.setBounds(1030, 200, 200, 200);

        btn_segundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn segundo.png"))); // NOI18N
        btn_segundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_segundoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_segundoMouseExited(evt);
            }
        });
        jPanel1.add(btn_segundo);
        btn_segundo.setBounds(600, 190, 200, 210);

        btn_regEmple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/relleno cuarto.png"))); // NOI18N
        btn_regEmple.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_regEmple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regEmpleMouseClicked(evt);
            }
        });
        jPanel1.add(btn_regEmple);
        btn_regEmple.setBounds(370, 390, 200, 210);

        btn_cuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn cuarto.png"))); // NOI18N
        btn_cuarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cuartoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cuartoMouseExited(evt);
            }
        });
        jPanel1.add(btn_cuarto);
        btn_cuarto.setBounds(370, 390, 210, 210);

        btn_rencu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/relleno quinto.png"))); // NOI18N
        btn_rencu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_rencu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_rencuMouseClicked(evt);
            }
        });
        jPanel1.add(btn_rencu);
        btn_rencu.setBounds(800, 400, 230, 210);

        btn_quinto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btn quinto.png"))); // NOI18N
        btn_quinto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_quintoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_quintoMouseExited(evt);
            }
        });
        jPanel1.add(btn_quinto);
        btn_quinto.setBounds(800, 400, 210, 210);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Perfil Sociodemografico");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(820, 600, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Evaluación Inicial");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 380, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Registro Empleados");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 590, 150, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Información de la Empresa");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(1030, 390, 200, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Llamados de Atención");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(630, 390, 160, 30);

        label_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PRINCIPAL3.jpg"))); // NOI18N
        jPanel1.add(label_fondo);
        label_fondo.setBounds(0, -10, 1370, 690);

        desktopPane.add(jPanel1);
        jPanel1.setBounds(1, 13, 1370, 683);

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        jm_realizarEvaIni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/notebook.png"))); // NOI18N
        jm_realizarEvaIni.setMnemonic('f');
        jm_realizarEvaIni.setText("Evaluacion Inicial");
        jm_realizarEvaIni.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jm_realizarEvaluacion.setMnemonic('o');
        jm_realizarEvaluacion.setText("Realizar Evaluacion Inicial");
        jm_realizarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_realizarEvaluacionActionPerformed(evt);
            }
        });
        jm_realizarEvaIni.add(jm_realizarEvaluacion);

        menuBar.add(jm_realizarEvaIni);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DIAGRAMA.png"))); // NOI18N
        jMenu3.setText("Perfil Socio-demografico");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenu3.add(jSeparator1);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/encuesta 1.2.png"))); // NOI18N
        jMenu5.setText("Encuesta SocioDemografica");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jm_RealizarEncuesta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jm_RealizarEncuesta.setText("Realizar Encuesta");
        jm_RealizarEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_RealizarEncuestaActionPerformed(evt);
            }
        });
        jMenu5.add(jm_RealizarEncuesta);

        jMenu3.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/archivo 2.png"))); // NOI18N
        jMenu4.setText("Administrar Encuestas");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jMenuItem1.setText("Habilitar Encuesta");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenu3.add(jMenu4);

        menuBar.add(jMenu3);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EMPLEADOS.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Empleados");
        editMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        me_registrarEmpleado.setMnemonic('t');
        me_registrarEmpleado.setText("Registrar Empleado");
        me_registrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                me_registrarEmpleadoActionPerformed(evt);
            }
        });
        editMenu.add(me_registrarEmpleado);

        menuBar.add(editMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/REPORTES.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Reportes");
        helpMenu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jm_evaluacionIni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/newspaper(1).png"))); // NOI18N
        jm_evaluacionIni.setText("Evaluacion Inicial");

        mn_items_cumple.setText("Estado de La Empresa (Items que Cumple)");
        mn_items_cumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_items_cumpleActionPerformed(evt);
            }
        });
        jm_evaluacionIni.add(mn_items_cumple);

        mn_itemnoCumple.setText("Por Alcanzar (Items que no Cumple)");
        mn_itemnoCumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_itemnoCumpleActionPerformed(evt);
            }
        });
        jm_evaluacionIni.add(mn_itemnoCumple);

        mn_veriCumple.setText("Documentacion y criterios (Verificaciones que cumplen)");
        mn_veriCumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_veriCumpleActionPerformed(evt);
            }
        });
        jm_evaluacionIni.add(mn_veriCumple);

        mn_criteriosNoCumple.setText("Documentacion y criterios por Alcanzar");
        mn_criteriosNoCumple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_criteriosNoCumpleActionPerformed(evt);
            }
        });
        jm_evaluacionIni.add(mn_criteriosNoCumple);

        mn_noaplica.setText("Items que la Empresa No Aplica");
        jm_evaluacionIni.add(mn_noaplica);

        helpMenu.add(jm_evaluacionIni);

        menuBar.add(helpMenu);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ATENCION.png"))); // NOI18N
        jMenu2.setText("Llamados de atencion");
        jMenu2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jm_realizarLlamadoAtencion.setText("Realizar Llamado de Atencion");
        jm_realizarLlamadoAtencion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jm_realizarLlamadoAtencionMouseClicked(evt);
            }
        });
        jMenu2.add(jm_realizarLlamadoAtencion);

        menuBar.add(jMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clipboard.png"))); // NOI18N
        jMenu1.setText("Empresa");

        jm_registrarEmpresa.setText("Registrar empresa");
        jm_registrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_registrarEmpresaActionPerformed(evt);
            }
        });
        jMenu1.add(jm_registrarEmpresa);

        menuBar.add(jMenu1);

        jmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.png"))); // NOI18N
        jmSalir.setText("Salir");
        jmSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSalirMouseClicked(evt);
            }
        });
        menuBar.add(jmSalir);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ayudaActionPerformed

    private void btn_ayudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ayudaMouseExited
        // TODO add your handling code here:
        if (!ayuda)
            Animacion.Animacion.mover_izquierda(0, -178, 1, 2, btn_ayuda);
    }//GEN-LAST:event_btn_ayudaMouseExited

    private void btn_ayudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ayudaMouseEntered
        // TODO add your handling code here:
        if(!ayuda)
        Animacion.Animacion.mover_derecha(-178, 0, 1, 2, btn_ayuda);
    }//GEN-LAST:event_btn_ayudaMouseEntered

    private void btn_acercaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acercaMouseExited
        // TODO add your handling code here:
        if (!acerca)
        Animacion.Animacion.mover_izquierda(0, -178, 1, 2, btn_acerca);
    }//GEN-LAST:event_btn_acercaMouseExited

    private void btn_acercaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_acercaMouseEntered
        // TODO add your handling code here:
        if(!acerca)
        Animacion.Animacion.mover_derecha(-178, 0, 1, 2, btn_acerca);
    }//GEN-LAST:event_btn_acercaMouseEntered

    private void btn_perfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_perfilActionPerformed
       panel_perfil.setVisible(true);
     
      
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_perfilActionPerformed

    private void btn_perfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perfilMouseExited
        // TODO add your handling code here:
        if (!perfil)
        Animacion.Animacion.mover_izquierda(0, -178, 1, 2, btn_perfil);
    }//GEN-LAST:event_btn_perfilMouseExited

    private void btn_perfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perfilMouseEntered
        // TODO add your handling code here:
        if(!perfil)
        Animacion.Animacion.mover_derecha(-178, 0, 1, 2, btn_perfil);
    }//GEN-LAST:event_btn_perfilMouseEntered

    private void jm_RealizarEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_RealizarEncuestaActionPerformed
        
       Encuesta_SocioDemografica realizarEncuesta=new Encuesta_SocioDemografica();
       M_EncuestaSocioDemografica modelo_encuesta=new M_EncuestaSocioDemografica();
         
       C_RealizarEncuesta controlador_realizarEncuesta=new C_RealizarEncuesta(realizarEncuesta, modelo_encuesta);
        
       realizarEncuesta.setVisible(true);
    }//GEN-LAST:event_jm_RealizarEncuestaActionPerformed

    private void Btn_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CerrarActionPerformed
panel_perfil.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_Btn_CerrarActionPerformed

   
    
    private void jmSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMouseClicked
    
        int opcionSalir = JOptionPane.showConfirmDialog(null,"Esta seguro que desea salir.");
        if (JOptionPane.YES_OPTION == opcionSalir){
           System.exit(0); 
        }
        
    }//GEN-LAST:event_jmSalirMouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void btn_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acercaActionPerformed
        
        panel_perfil.setVisible(false);
     //  Panel_Acerca.setVisible(true);
        
        
      
        
        
        

// TODO add your handling code here:
    }//GEN-LAST:event_btn_acercaActionPerformed

    private void jm_realizarLlamadoAtencionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jm_realizarLlamadoAtencionMouseClicked
      vista_llamadosAtencion=new Llamados_Atencion();
        vista_llamadosAtencion.setVisible(true);
    }//GEN-LAST:event_jm_realizarLlamadoAtencionMouseClicked

    private void mn_items_cumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_items_cumpleActionPerformed
         Map p= new HashMap();
        JasperReport repor;
        JasperPrint print;
        
        try {
            repor= JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpcumitem.jrxml");
            print= JasperFillManager.fillReport(repor, p,connection);
           JasperViewer view= new JasperViewer(print, false);
            view.setTitle("Reporte de la documentacion y criterios que no cumple la empresa");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mn_items_cumpleActionPerformed

    private void mn_itemnoCumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_itemnoCumpleActionPerformed
        Map p= new HashMap();
        JasperReport repor;
        JasperPrint print;
        
        try {
            repor= JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpnocumitem.jrxml");
            print= JasperFillManager.fillReport(repor, p,connection);
           JasperViewer view= new JasperViewer(print, false);
            view.setTitle("Reporte de la documentacion y criterios que cumple la empresa");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mn_itemnoCumpleActionPerformed

    private void mn_veriCumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_veriCumpleActionPerformed
        Map p= new HashMap();
        JasperReport repor;
        JasperPrint print;
        
        try {
            repor= JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpcumveri.jrxml");
            print= JasperFillManager.fillReport(repor, p,connection);
           JasperViewer view= new JasperViewer(print, false);
            view.setTitle("Reporte de la documentacion y criterios que cumple la empresa");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mn_veriCumpleActionPerformed

    private void mn_criteriosNoCumpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_criteriosNoCumpleActionPerformed
         Map p= new HashMap();
        JasperReport repor;
        JasperPrint print;
        
        try {
            repor= JasperCompileManager.compileReport(new File("").getAbsolutePath()+"/src/Reportes/rpnocumveri.jrxml");
            print= JasperFillManager.fillReport(repor, p,connection);
           JasperViewer view= new JasperViewer(print, false);
            view.setTitle("Reporte de la documentacion y criterios que no cumple la empresa");
            view.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mn_criteriosNoCumpleActionPerformed

    private void jm_realizarEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_realizarEvaluacionActionPerformed
        Evaluacion_Ini vista_evaluacion=new Evaluacion_Ini();
        vista_evaluacion.toFront();
        vista_evaluacion.setVisible(true);
    }//GEN-LAST:event_jm_realizarEvaluacionActionPerformed

    private void btn_primeroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_primeroMouseEntered
       btn_evaluacion.setVisible(true);
    }//GEN-LAST:event_btn_primeroMouseEntered

    private void btn_primeroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_primeroMouseExited
btn_evaluacion.setVisible(false);
    }//GEN-LAST:event_btn_primeroMouseExited

    private void btn_segundoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_segundoMouseEntered
        btn_relleno2.setVisible(true);
    }//GEN-LAST:event_btn_segundoMouseEntered

    private void btn_segundoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_segundoMouseExited
      btn_relleno2.setVisible(false);
    }//GEN-LAST:event_btn_segundoMouseExited

    private void btn_cuartoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cuartoMouseEntered
     btn_regEmple.setVisible(true);
    }//GEN-LAST:event_btn_cuartoMouseEntered

    private void btn_cuartoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cuartoMouseExited
        btn_regEmple.setVisible(false);
    }//GEN-LAST:event_btn_cuartoMouseExited

    private void btn_quintoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quintoMouseEntered
        btn_rencu.setVisible(true);
    }//GEN-LAST:event_btn_quintoMouseEntered

    private void btn_quintoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_quintoMouseExited
        btn_rencu.setVisible(false);
    }//GEN-LAST:event_btn_quintoMouseExited

    private void btn_terceroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_terceroMouseEntered
      btn_relleno3.setVisible(true);
    }//GEN-LAST:event_btn_terceroMouseEntered

    private void btn_terceroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_terceroMouseExited
      btn_relleno3.setVisible(false);
    }//GEN-LAST:event_btn_terceroMouseExited

    private void btn_evaluacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_evaluacionMouseClicked
         Evaluacion_Ini vista_evaluacion=new Evaluacion_Ini();
       vista_evaluacion.toFront();
        vista_evaluacion.setVisible(true);
    }//GEN-LAST:event_btn_evaluacionMouseClicked

    private void btn_regEmpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regEmpleMouseClicked
          RegistroEmpleados vista=new RegistroEmpleados();
                M_RegistrarEmpleado modelo=new M_RegistrarEmpleado();
                C_RegistrarEmpleado controlador=new C_RegistrarEmpleado(vista,modelo);
                
                vista.setVisible(true);
    }//GEN-LAST:event_btn_regEmpleMouseClicked

    private void btn_rencuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_rencuMouseClicked
        Encuesta_SocioDemografica realizarEncuesta=new Encuesta_SocioDemografica();
       M_EncuestaSocioDemografica modelo_encuesta=new M_EncuestaSocioDemografica();
          
       C_RealizarEncuesta controlador_realizarEncuesta=new C_RealizarEncuesta(realizarEncuesta, modelo_encuesta);
        
       realizarEncuesta.setVisible(true);
    }//GEN-LAST:event_btn_rencuMouseClicked

    private void btn_primeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_primeroMouseClicked
        
    }//GEN-LAST:event_btn_primeroMouseClicked

    private void jm_registrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_registrarEmpresaActionPerformed
         Registro_Empresa gh = new Registro_Empresa();
        gh.toFront();
        gh.setVisible(true);
    }//GEN-LAST:event_jm_registrarEmpresaActionPerformed

    private void me_registrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_me_registrarEmpleadoActionPerformed
        RegistroEmpleados vista=new RegistroEmpleados();
        M_RegistrarEmpleado modelo=new M_RegistrarEmpleado();
        C_RegistrarEmpleado controlador=new C_RegistrarEmpleado(vista,modelo);

        vista.setVisible(true);
    }//GEN-LAST:event_me_registrarEmpleadoActionPerformed

    private void txt_nombrePriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombrePriActionPerformed
        
    }//GEN-LAST:event_txt_nombrePriActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        HabEncuestaTodos vista_habEncuTodos=new HabEncuestaTodos();
        M_HabEncuTodos modelo_habEncuTodos= new M_HabEncuTodos();
        C_HabEncuTodos controlador_habEncuTodos=new C_HabEncuTodos(vista_habEncuTodos, modelo_habEncuTodos);
        vista_habEncuTodos.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      try{
            UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");
        }catch(Exception e){
            
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cerrar;
    private javax.swing.JButton btnEditar_Perfil;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btn_acerca;
    private javax.swing.JButton btn_ayuda;
    private javax.swing.JLabel btn_cuarto;
    public javax.swing.JLabel btn_evaluacion;
    private javax.swing.JButton btn_perfil;
    public javax.swing.JLabel btn_primero;
    private javax.swing.JLabel btn_quinto;
    public javax.swing.JLabel btn_regEmple;
    private javax.swing.JLabel btn_relleno2;
    private javax.swing.JLabel btn_relleno3;
    public javax.swing.JLabel btn_rencu;
    private javax.swing.JLabel btn_segundo;
    private javax.swing.JLabel btn_tercero;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jm_RealizarEncuesta;
    private javax.swing.JMenu jm_evaluacionIni;
    public javax.swing.JMenu jm_realizarEvaIni;
    public javax.swing.JMenuItem jm_realizarEvaluacion;
    private javax.swing.JMenu jm_realizarLlamadoAtencion;
    public javax.swing.JMenuItem jm_registrarEmpresa;
    private javax.swing.JLabel label_fondo;
    public javax.swing.JLabel label_nombreUser;
    public javax.swing.JLabel label_rol;
    private javax.swing.JLabel lbl_fondoPerfil;
    private javax.swing.JLabel lbl_safetyNom;
    private javax.swing.JLabel logo;
    public javax.swing.JMenuItem me_registrarEmpleado;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mn_criteriosNoCumple;
    private javax.swing.JMenuItem mn_itemnoCumple;
    private javax.swing.JMenuItem mn_items_cumple;
    private javax.swing.JMenuItem mn_noaplica;
    private javax.swing.JMenuItem mn_veriCumple;
    private javax.swing.JPanel panel_perfil;
    private javax.swing.JLabel txt_Nombres;
    private javax.swing.JLabel txt_PrimerApellido;
    private javax.swing.JLabel txt_nombrePerfil;
    public javax.swing.JTextField txt_nombrePri;
    // End of variables declaration//GEN-END:variables

  

}
